# Generated by Django 5.1.3 on 2024-12-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("florist", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactModel",
            new_name="Contact_Model",
        ),
    ]
